Repository ae-bii/neural-geometry, pull requests merged in 2024-07, with the labels that each got.

#30 Update project description in pyproject.toml
  pyproject.toml
Labels: documentation

#34 Hotfix: Fix dependencies for project when installing from PyPI
  .travis.yml
  README.md
  pyproject.toml
  requirements.txt
Labels: bug

#37 Feature/searchspace-manifolds-tests-fix
  .github/workflows/python-test.yaml
  nlgm/manifolds.py
  nlgm/searchspace.py
  pyproject.toml
  test/dummy_test.py
  test/test_manifolds.py
  test/test_searchspace.py
  tox.ini
Labels: enhancement
